rtabmap:
  ros__parameters:
    use_sim_time: True
    frame_id: base_link
    odometry_frame_id: odom
    #publish_tf: true
    subscribe_depth: True
    subscribe_rgbd: True
    subscribe_scan: True
    use_action_for_goal: True
    approx_sync: True
    rgb_topic: /camera_depth/image_raw
    camera_info_topic: /camera_depth/depth/camera_info
    depth_topic: /camera_depth/depth/image_raw
    #Rtabmap/PublishGrid: True
    #RGBD/PublishCloud: True
    Reg/Force3DoF: True
    Grid/RayTracing: True # Fill empty space
    #Grid/FromDepth: True
    Grid/3D: False # Use 2D occupancy
    Grid/RangeMax: 3
    Grid/NormalsSegmentation: False # Use passthrough filter to detect obstacles
    Grid/MaxGroundHeight: 0.05 # All points above 5 cm are obstacles
    Grid/MaxObstacleHeight: 0.4  # All points over 1 meter are ignored
    Optimizer/GravitySigma: 0 # Disable imu constraints (we are already in 2D)
