name: Build ROS Packages

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble  # change to your distro

      - name: Build package
        run: |
          mkdir -p ~/ros_ws/src
          cp -R $GITHUB_WORKSPACE/* ~/ros_ws/src/
          cd ~/ros_ws
          cd $GITHUB_WORKSPACE
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          source /opt/ros/humble/setup.sh
          colcon build --packages-select auto_bot --cmake-args -DCMAKE_BUILD_TYPE=Release
          source install/setup.sh
